-------- Transacciones por dia - SUPERPACK-CLARO - Marzo 2026
-------- Para comparar contra grafica "Trx por dia" del dashboard
SELECT
  CAST(DW_MUL_SPPADAT.DW_FECHA_OPERACION_SP AS DATE) AS Fecha,
  COUNT(*)                                            AS TotalTransacciones,
  COUNT(DISTINCT ClientesBel.CLCCLI)                  AS ClientesUnicos

FROM
  DW_MUL_SPPADAT
    LEFT JOIN DW_MUL_SPMACO ON DW_MUL_SPMACO.SPCODC = DW_MUL_SPPADAT.SPCODC
    LEFT JOIN (
      SELECT
        LTRIM(RTRIM(DW_BEL_IBUSER.CLCCLI)) CLCCLI,
        LTRIM(RTRIM(DW_BEL_IBUSER.USCODE)) USCODE
      FROM DW_BEL_IBUSER
    ) ClientesBel ON LTRIM(RTRIM(DW_MUL_SPPADAT.SPINUS)) = (ClientesBel.CLCCLI + ClientesBel.USCODE)
    LEFT JOIN (
      SELECT LTRIM(RTRIM(CLDOC)) CLDOC, CLTIPE,
        ROW_NUMBER() OVER (
          PARTITION BY LTRIM(RTRIM(CLDOC))
          ORDER BY CASE WHEN CLTIPE = 'N' THEN 1 WHEN CLTIPE IS NULL THEN 2 ELSE 3 END
        ) AS RN
      FROM DW_CIF_CLIENTES
    ) CIF ON CIF.CLDOC = ClientesBel.CLCCLI AND CIF.RN = 1

WHERE
  DW_MUL_SPPADAT.DW_FECHA_OPERACION_SP >= '2026-03-01'
  AND DW_MUL_SPPADAT.DW_FECHA_OPERACION_SP <  '2026-04-01'
  AND DW_MUL_SPPADAT.SPCPCO IN (1, 7)
  AND DW_MUL_SPPADAT.SPCODC = 498
  AND (CIF.CLTIPE <> 'J' OR CIF.CLTIPE IS NULL)

GROUP BY CAST(DW_MUL_SPPADAT.DW_FECHA_OPERACION_SP AS DATE)
ORDER BY Fecha
