-- Comparacion interanual de marzo: 2024, 2025 y 2026
-- Cohorte: cuentas que abrieron en marzo de cada año y tuvieron saldo > 0 ese mismo mes

WITH Marzo2024 AS (
    SELECT DISTINCT DW_CUENTA_CORPORATIVA
    FROM dw_dep_depositos
    WHERE dw_feha_apertura BETWEEN '2024-03-01' AND '2024-03-31'
      AND dw_producto = 'CUENTA DIGITAL'
      AND PRCODP = 1 AND PRSUBP = 51
),
Marzo2025 AS (
    SELECT DISTINCT DW_CUENTA_CORPORATIVA
    FROM dw_dep_depositos
    WHERE dw_feha_apertura BETWEEN '2025-03-01' AND '2025-03-31'
      AND dw_producto = 'CUENTA DIGITAL'
      AND PRCODP = 1 AND PRSUBP = 51
),
Marzo2026 AS (
    SELECT DISTINCT DW_CUENTA_CORPORATIVA
    FROM dw_dep_depositos
    WHERE dw_feha_apertura BETWEEN '2026-03-01' AND '2026-03-31'
      AND dw_producto = 'CUENTA DIGITAL'
      AND PRCODP = 1 AND PRSUBP = 51
)

SELECT 'Marzo 2024' AS mes, 1 AS orden,
    COUNT(DISTINCT u.DW_CUENTA_CORPORATIVA) AS cuentas_abiertas,
    COUNT(DISTINCT CASE WHEN h.ctt001 > 0 THEN u.DW_CUENTA_CORPORATIVA END) AS cuentas_fondeadas
FROM Marzo2024 u
LEFT JOIN HIS_DEP_DEPOSITOS_VIEW h
    ON u.DW_CUENTA_CORPORATIVA = h.DW_CUENTA_CORPORATIVA
    AND h.dw_fecha_informacion BETWEEN '2024-03-01' AND '2024-03-31'

UNION ALL

SELECT 'Marzo 2025', 2,
    COUNT(DISTINCT u.DW_CUENTA_CORPORATIVA),
    COUNT(DISTINCT CASE WHEN h.ctt001 > 0 THEN u.DW_CUENTA_CORPORATIVA END)
FROM Marzo2025 u
LEFT JOIN HIS_DEP_DEPOSITOS_VIEW h
    ON u.DW_CUENTA_CORPORATIVA = h.DW_CUENTA_CORPORATIVA
    AND h.dw_fecha_informacion BETWEEN '2025-03-01' AND '2025-03-31'

UNION ALL

SELECT 'Marzo 2026', 3,
    COUNT(DISTINCT u.DW_CUENTA_CORPORATIVA),
    COUNT(DISTINCT CASE WHEN h.ctt001 > 0 THEN u.DW_CUENTA_CORPORATIVA END)
FROM Marzo2026 u
LEFT JOIN HIS_DEP_DEPOSITOS_VIEW h
    ON u.DW_CUENTA_CORPORATIVA = h.DW_CUENTA_CORPORATIVA
    AND h.dw_fecha_informacion BETWEEN '2026-03-01' AND '2026-03-31'

ORDER BY orden;
