SELECT count(
  DW_CIF_CLIENTES.CLDOC)

FROM
  DW_CIF_CLIENTES
WHERE
  (
   DW_CIF_CLIENTES.dw_usuarios_bel_cnt > 0
   AND
   DW_CIF_CLIENTES.ESTATU  IN  ( 'A'  )
   AND
   DW_CIF_CLIENTES.DW_FECHA_NACIMIENTO <= DATEADD(YEAR,-18,GETDATE())
   AND
   DW_CIF_CLIENTES.CLTIPE  IN  ( 'N'  )
  )


